FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        tesseract-ocr \
        tesseract-ocr-por \
        poppler-utils \
        libgl1 \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-etl.txt .
RUN pip install --no-cache-dir -r requirements-etl.txt

COPY etl/ ./etl/
COPY data/ ./data/

CMD ["python", "-m", "etl.run_etl"]
