FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# pre-baixa o modelo durante o build
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

COPY api/ ./api/
COPY retrieval/ ./retrieval/
COPY generation/ ./generation/
COPY index.html ./index.html

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
